Repository Metropolitan-Council/councilR, pull requests merged in 2022-01, with the labels that each got.

#18 Create scale_fill_council.R
  R/scale_fill_council.R
Labels: template

#21 Unable to install with tibble error
  .github/workflows/R-CMD-check.yaml
  DESCRIPTION
  R/scale_fill_council.R
  man/council.pal.Rd
  man/import_from_gis.Rd
  man/import_from_gpkg.Rd
  man/snippets_install.Rd
Labels: bug

#16 Add snippets for metro and tile CRS codes
  .github/workflows/R-CMD-check.yaml
  inst/snippets/r.snippets
Labels: enhancement, wouldn't it be nice
